// Auto-generated by tools/convert_sprites.py — DO NOT EDIT BY HAND.
#pragma once
#include <Arduino.h>
#include <stdint.h>

constexpr uint16_t SPRITE_TRANSPARENT = 0xF81F;

constexpr uint16_t FACE_W = 108;
constexpr uint16_t FACE_H = 36;
constexpr uint16_t EYES_W = 136;
constexpr uint16_t EYES_H = 8;
constexpr uint16_t MOUTHS_W = 204;
constexpr uint16_t MOUTHS_H = 8;

// Tile dims.
constexpr uint16_t FACE_TILE_W = 36;
constexpr uint16_t FACE_TILE_H = 36;
constexpr uint16_t EYES_TILE_W = 17;
constexpr uint16_t EYES_TILE_H = 8;
constexpr uint16_t MOUTHS_TILE_W = 17;
constexpr uint16_t MOUTHS_TILE_H = 8;

// Eyes/mouth offsets inside a face tile (CircuitPython source: EYE_REL_*, MOUTH_REL_*).
constexpr uint16_t EYE_REL_X = 12;
constexpr uint16_t EYE_REL_Y = 8;
constexpr uint16_t MOUTH_REL_X = 12;
constexpr uint16_t MOUTH_REL_Y = 16;

extern const uint16_t FACE_PIXELS[FACE_W * FACE_H] PROGMEM;
extern const uint16_t EYES_PIXELS[EYES_W * EYES_H] PROGMEM;
extern const uint16_t MOUTHS_PIXELS[MOUTHS_W * MOUTHS_H] PROGMEM;
