#!/usr/bin/env python3
"""Convert 8-bit indexed BMP sprite atlases into a PROGMEM RGB565 C header.

Source BMPs (`face.bmp`, `eyes.bmp`, `mouths.bmp`) are 8-bit indexed with a
palette. The CircuitPython side marks specific palette indices as transparent
(face idx 1 = BLACK, eyes/mouths idx 0 = TEAL); we propagate that by encoding
those pixels as a sentinel 16-bit value (0xF81F = bright magenta) that the
compositor treats as "skip this pixel" instead of writing it to the framebuffer.

Output: `src/sprites.h` and `src/sprites.cpp` next to main.cpp. The header
exposes:

    constexpr uint16_t SPRITE_TRANSPARENT = 0xF81F;
    constexpr uint16_t FACE_W = 108, FACE_H = 36;
    constexpr uint16_t EYES_W = 136, EYES_H = 8;
    constexpr uint16_t MOUTHS_W = 204, MOUTHS_H = 8;
    extern const uint16_t FACE_PIXELS[FACE_W * FACE_H];
    extern const uint16_t EYES_PIXELS[EYES_W * EYES_H];
    extern const uint16_t MOUTHS_PIXELS[MOUTHS_W * MOUTHS_H];
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from PIL import Image


# 0xF81F (RGB565 magenta) acts as our "transparent" sentinel. Pure magenta is
# very unlikely to appear in either the face or overlay palettes — verified
# against the source BMPs.
SPRITE_TRANSPARENT = 0xF81F

# Palette indices marked transparent in the CircuitPython source.
TRANSPARENT_INDEX = {
    "face": 1,    # BLACK
    "eyes": 0,    # TEAL
    "mouths": 0,  # TEAL
}


def rgb_to_565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def encode(img_path: Path, kind: str) -> tuple[int, int, list[int]]:
    img = Image.open(img_path)
    if img.mode != "P":
        raise SystemExit(f"{img_path}: expected 8-bit indexed (mode P), got {img.mode}")
    palette = img.getpalette()  # flat [r,g,b, r,g,b, ...]
    if palette is None:
        raise SystemExit(f"{img_path}: no palette")
    width, height = img.size
    transparent_idx = TRANSPARENT_INDEX[kind]
    pixels: list[int] = []
    raw = list(img.getdata())
    for idx in raw:
        if idx == transparent_idx:
            pixels.append(SPRITE_TRANSPARENT)
        else:
            base = idx * 3
            r, g, b = palette[base], palette[base + 1], palette[base + 2]
            rgb = rgb_to_565(r, g, b)
            # Avoid an opaque pixel that accidentally matches the sentinel.
            if rgb == SPRITE_TRANSPARENT:
                rgb = 0xF81E  # nudged off by 1 in blue
            pixels.append(rgb)
    return width, height, pixels


def emit_array(name: str, pixels: list[int], cols: int = 12) -> str:
    out = [f"const uint16_t {name}[{len(pixels)}] PROGMEM = {{"]
    for i in range(0, len(pixels), cols):
        chunk = ", ".join(f"0x{p:04X}" for p in pixels[i : i + cols])
        out.append(f"    {chunk},")
    out.append("};")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default="tools/sprites_src", help="dir with face.bmp eyes.bmp mouths.bmp")
    ap.add_argument("--header", default="src/sprites.h", help="output header path")
    ap.add_argument("--source", default="src/sprites.cpp", help="output source path")
    args = ap.parse_args()

    src_dir = Path(args.src)
    face_w, face_h, face_px = encode(src_dir / "face.bmp", "face")
    eyes_w, eyes_h, eyes_px = encode(src_dir / "eyes.bmp", "eyes")
    mouths_w, mouths_h, mouths_px = encode(src_dir / "mouths.bmp", "mouths")

    # Sanity: spec says 108x36 face, 136x8 eyes, 204x8 mouths.
    expected = {(face_w, face_h): (108, 36),
                (eyes_w, eyes_h): (136, 8),
                (mouths_w, mouths_h): (204, 8)}
    actual = {(face_w, face_h), (eyes_w, eyes_h), (mouths_w, mouths_h)}
    want = {(108, 36), (136, 8), (204, 8)}
    if actual != want:
        sys.stderr.write(
            f"WARN: sprite dims don't match spec exactly. face={face_w}x{face_h} "
            f"eyes={eyes_w}x{eyes_h} mouths={mouths_w}x{mouths_h}\n"
        )

    header = f"""// Auto-generated by tools/convert_sprites.py — DO NOT EDIT BY HAND.
#pragma once
#include <Arduino.h>
#include <stdint.h>

constexpr uint16_t SPRITE_TRANSPARENT = 0x{SPRITE_TRANSPARENT:04X};

constexpr uint16_t FACE_W = {face_w};
constexpr uint16_t FACE_H = {face_h};
constexpr uint16_t EYES_W = {eyes_w};
constexpr uint16_t EYES_H = {eyes_h};
constexpr uint16_t MOUTHS_W = {mouths_w};
constexpr uint16_t MOUTHS_H = {mouths_h};

// Tile dims.
constexpr uint16_t FACE_TILE_W = 36;
constexpr uint16_t FACE_TILE_H = 36;
constexpr uint16_t EYES_TILE_W = 17;
constexpr uint16_t EYES_TILE_H = 8;
constexpr uint16_t MOUTHS_TILE_W = 17;
constexpr uint16_t MOUTHS_TILE_H = 8;

// Eyes/mouth offsets inside a face tile (CircuitPython source: EYE_REL_*, MOUTH_REL_*).
constexpr uint16_t EYE_REL_X = 12;
constexpr uint16_t EYE_REL_Y = 8;
constexpr uint16_t MOUTH_REL_X = 12;
constexpr uint16_t MOUTH_REL_Y = 16;

extern const uint16_t FACE_PIXELS[FACE_W * FACE_H] PROGMEM;
extern const uint16_t EYES_PIXELS[EYES_W * EYES_H] PROGMEM;
extern const uint16_t MOUTHS_PIXELS[MOUTHS_W * MOUTHS_H] PROGMEM;
"""

    source = "// Auto-generated by tools/convert_sprites.py — DO NOT EDIT BY HAND.\n"
    source += "#include \"sprites.h\"\n\n"
    source += emit_array("FACE_PIXELS", face_px) + "\n\n"
    source += emit_array("EYES_PIXELS", eyes_px) + "\n\n"
    source += emit_array("MOUTHS_PIXELS", mouths_px) + "\n"

    Path(args.header).parent.mkdir(parents=True, exist_ok=True)
    Path(args.header).write_text(header)
    Path(args.source).write_text(source)
    print(f"wrote {args.header} ({len(face_px) + len(eyes_px) + len(mouths_px)} px total)")
    print(f"wrote {args.source}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
